language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest tests
deploy:
  provider: lambda
  function_name: "jobbie-store"
  region: "us-east-1"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  role: $ROLE
  runtime: "python3.7"
  module_name: "app"
  handler_name: "lambda_handler"