language: python
python:
- '3.6'
branches:
  only: master
install:
- pip install -r requirements.txt
- pip install awscli
- pip install aws-sam-cli
script:
- sam validate
- sam package --template-file template.yaml --s3-bucket jobbie-store --output-template-file packaged.yaml
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --stack-name jobbie-store-stack --capabilities CAPABILITY_IAM
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - AWS_DEFAULT_REGION: "$AWS_DEFAULT_REGION"
  - secure: aNEfPzGuv2dL51cHeys0vYsQ5QByua3X2qn/WVr+JGC+sEBSYyjKubti+29TyG3J2kh6BBZRbvy07LQvgsqb6O4Abxn0gLk6BB+xRXJRSA3zr+TA89wLURiNY7omvLpNiFnVz83ZK161b9IFQiGpnzGBfZerOCKdBCY6aPb94LXNKDBJQDx5KEFDovJoq2AwpDdIlgBNNUqGt0DPMoLbf/fWpxVMAPsBRe5dOCC/j21XcJGoD1uDX7b/LB5zulhOT9yvLeK3iRBRDk0ZEjFcD7ERacB3kXK+kvVYgKVjZ8F9mLkFBarGQYjbUY+w7eVXuZJPq1ky2nfEQU54zhJ8HVpBaDAO++4K/A/4ux5k5w79wl4wMLLmZDjTlQqwprKfR18t559KBk/SvMuOMQKCpOYN8F9GXYgEbiTTtIJ+no6Ew26jXGrC9ElCCXlQbmYPHaGZ1ZC0vB5u4fYJ/7E6h7zY6R3krNwwbl2C35fDprDgNjVcL8+OigsfEqD5eQGSqJTrsqf5tQ8IvKF727zTN2Id3QTndfZ9SzuVORHc+SXZIV9ztgd9tBy7aPDkegdqhrmb0qzZ/QF4AU65BEYh8vPKNVSoVJJ0X8to4qlywuZRhAWSdGVSvhlVeBdpU2iyIjakRxn37xpaBIaUwzvwZnpPhOG5tw+UztCXZCbLaz0=
  - secure: ffxU9IWJEYWZerC8+MCYG/GXS57zebi0Sdavb5xCY52OcEKTZCrx2FDRatoI3vXPTsjLjh4lz3ic9HveIdjw5r1Lm0NsNVsaT/KkAt6vpOfK0xRW1lqjT9RKnftnfLD4CH0tl4yeSrYm5eQ5H3hRZP9gt0b8NO3ECRDZ05IoT6PCO2xrZ+QCl7qU6DiXX6bQJaH+uNXCs8HLbi3yqN+5o90i1RNc2g39iqMxxxzFTfrfWyyLpSANtQ6t/yagoADO/W86b9N21eaiEOxDtMCXADHjoWROaThtEaSAoMd9FK5Uw8QI1aG/lS+ACXoKgb+1EbLltB42YqEAnTEXytFOAewYqQzEreaD6qA40AeMbhno9AQIFpvdx1cZ0CLlrn8uLTJZADXDZVRJZtI9/ZzpQiVwz+Xn8Yb87Upy1FMejqlOGHI8BMwznrjeHqnTzMIMr7IB7PnywqGuVIcbGSgHw6ze/H11BHvjE1+IZ465WBHUHRSNuncgWaslghuH54jkU1JY4HeRFGZyO63ZD9Shequ5qf/lvJf7Mox8lpUp/jiRvZH4lvMOOc9l+R/ZRdCMEZy7cryKklab/hklwJsz7WBTCSqy91/oPgJGAVjtFuhbfelM/fv4F4B5+0Xod89U72KyRsgVXA6+68xYVUq9inPy1f6KihyeE2Fa1R5j5LM=
