AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jobbie-store

  Stores the job offers collected into the DB

Globals:
  Function:
    Timeout: 3

Resources:
  JobbieStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        JobbieCollectorEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobbieCollectorQueue.Arn
            BatchSize: 10

  JobbieCollectorQueue:
    Type: AWS::SQS::Queue