AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jobbie-store

  Stores the job offers collected into the DB

Globals:
  Function:
    Timeout: 3

Parameters:
  TABLE_NAME:
    Type: String
    Description: The DynamoDB table for storing the Jobs information.
    Default: 'JobsTable'

  QUEUE_NAME:
    Type: String
    Description: The Queue that contains the job events
    Default: 'JobsQueue'

Resources:
  JobbieStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        JobbieCollectorEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          TABLE_NAME: !Ref TABLE_NAME
          QUEUE_NAME: !Ref QUEUE_NAME

  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QUEUE_NAME

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TABLE_NAME
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
